apiVersion: v1
kind: Namespace
metadata:
  name: kube-serve
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-ssh
  labels:
    app: ubuntu-ssh
  namespace: kube-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-ssh
  template:
    metadata:
      labels:
        app: ubuntu-ssh
    spec:
      containers:
        - name: ubuntu-ssh
          env:
            - name: SSH_USER
              value: k8ssshuser
            - name: SSH_PASSWORD
              value: k8ssshpassword
          image: zhiqiangwang/tunnel:ssh
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 22
              name: tcp-22
              protocol: TCP
