apiVersion: v1
kind: Namespace
metadata:
  name: kube-serve
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray-tunnel
  labels:
    app: v2ray-tunnel
  namespace: kube-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2ray-tunnel
  template:
    metadata:
      labels:
        app: v2ray-tunnel
    spec:
      containers:
        - name: v2ray-tunnel
          env:
            - name: V2RAY_VMESS_PORT
              value: "10086"
            - name: V2RAY_CLIENT_ID
              value: "b831381d-6324-4d53-ad4f-8cda48b30811"
          image: zhiqiangwang/tunnel:v2ray
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
          ports:
            - containerPort: 10086
              name: tcp-10086
              protocol: TCP
