apiVersion: v1
kind: Namespace
metadata:
  name: kube-serve
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-tunnel
  labels:
    app: xray-tunnel
  namespace: kube-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xray-tunnel
  template:
    metadata:
      labels:
        app: xray-tunnel
    spec:
      containers:
        - name: xray-tunnel
          env:
            - name: XRAY_VMESS_PORT
              value: "9000"
            - name: XRAY_CLIENT_ID
              value: "1eb6e917-774b-4a84-aff6-b058577c60a5"
          image: zhiqiangwang/tunnel:xray
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9000
              name: tcp-9000
              protocol: TCP
